### PR TITLE
Final changes

### PR DESCRIPTION
**Pull request by victorg1991**
@mdelapenya I haven't change the ActivitiyIndicator variable names because I take it from RxSwift example

### CODE REVIEW

**Comment by javierlopezdeancos** [comment]
@victorg1991 swift can render svg files? I can provide you an svg with the logo :)

**Comment by victorg1991** [comment]
@javierlopezdeancos As far as I know, iOS can render vector images, but only in .pdf format. If you can generate that I will add it to the project

Thanks! :D

**Comment by javierlopezdeancos** [comment]
I think that maybe this approach is better to render with good quality, I think that I can export the svg in pdf and push in https://github.com/craftsmanship-toledo/katangapp-ivc/tree/dev
this afternoon I can do it!!

**Comment by mdelapenya** [comment]
@javierlopezdeancos, let us merge this pull, and then you are welcome to send the pull whenever you are ready :) Thank you bro!

**Comment by javierlopezdeancos** [comment]
I agree with you @mdelapenya , merge!!

**Pull request merged**
